# Generated by Django 2.2.4 on 2020-06-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('covid', models.CharField(max_length=20)),
                ('sintomas', models.CharField(choices=[('Fie', 'Fiebre'), ('ToS', 'Tos seca'), ('Can', 'Cansancio'), ('MoD', 'Molestias y Dolores'), ('Gar', 'Dolor de Garganta'), ('Diar', 'Diarrea'), ('Conj', 'Conjuntivitis'), ('DC', 'Dolores de cabeza'), ('Per', 'Pérdida del olfato o del gusto'), ('PerC', 'Erupciones cutáneas o pérdida del color en extremidades'), ('Resp', 'Insuficiencia Respiratorias'), ('Dif', 'Dificultad para respirar o sensación de falta de aire'), ('DolPe', 'Dolor o presión en el pecho'), ('Inc', 'Incapacidad para hablar o moverse')], max_length=5)),
            ],
        ),
    ]
