# Generated by Django 2.2.4 on 2020-06-24 00:57

from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='fecha',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registros',
            name='muerte',
            field=models.IntegerField(null=True, blank=True, verbose_name=1),
            preserve_default=False,
        ),
    ]
