# Generated by Django 2.2.4 on 2020-06-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0002_auto_20200624_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='muerte',
        ),
    ]
